app/forms/pending_game.py
from flask_wtf import FlaskForm
from wtforms import IntegerField, SubmitField, HiddenField
from wtforms.validators import DataRequired, Length, Regexp


class PendingGameForm(FlaskForm):
    game_id      = HiddenField('Game id')
    new_game     = SubmitField('New game')
    restore_game = SubmitField('Restore last game')

app/blueprints/gui.py
from flask import Blueprint,render_template, flash, get_flashed_messages, request, redirect, url_for, session

from flask_login import login_required, current_user, logout_user

from app import app,login_manager
from app.models.hangman import Hangman
from app.models.user import User
from app.forms.game import GameForm
from app.forms.pending_game import PendingGameForm
from app.errors.api import RefreshTokenExpiredError
from app.api.api_interface import APIInterface


gui = Blueprint('gui',__name__)


@gui.route('/')
@login_required
def home():
    return render_template('home.html')


@gui.route('/halloffame')
def halloffame():
    try:
        games = APIInterface.getHallOfFame()
    except RefreshTokenExpiredError as e:
        # Refresh token expired, we have to log in again
        flash('Session expired. Log in again','is-danger')
        return redirect(url_for('auth.logout'))
    except Exception as e:
        flash('Failed to retrieve Hall of Fame. {}'.format(e),'is-danger')
        return render_template('halloffame.html')

    return render_template('halloffame.html',games=games)

'''
@gui.route('/play')
@login_required
def play():
    user = current_user
    hangman = Hangman()
    try:
        hangman.startGame()
    except RefreshTokenExpiredError as e:
        # Refresh token expired, we have to log in again
        flash('Session expired. Log in again','is-danger')
        return redirect(url_for('auth.logout'))
    except Exception as e:
        flash('Failed to start game. {}'.format(e),'is-danger')
        return render_template('home.html')
    
    return render_template('play.html', hangman = hangman, form = GameForm())
'''


@gui.route('/play')
@login_required
def play():
  
    try:
        games = APIInterface.getUserLastActiveGame(current_user.id)
    except RefreshTokenExpiredError as e:
        # Refresh token expired, we have to log in again
        flash('Session expired. Log in again','is-danger')
        return redirect(url_for('auth.logout'))
    except Exception as e:
        flash('Failed to retrieve last game. {}'.format(e),'is-danger')
        return render_template('home.html')

    # There are active games
    if len(games) > 0:
        # Games is a one game list
        game = games[0]
        form = PendingGameForm()
        form.game_id.data = game.get('id')
        return render_template('pending_game.html', game = game, form = form )

    hangman = Hangman()
    try:
        hangman.startGame()
    except RefreshTokenExpiredError as e:
        # Refresh token expired, we have to log in again
        flash('Session expired. Log in again','is-danger')
        return redirect(url_for('auth.logout'))
    except Exception as e:
        flash('Failed to start game. {}'.format(e),'is-danger')
        return render_template('home.html')
    
    return render_template('play.html', hangman = hangman, form = GameForm())


@gui.route('/play',methods=['POST'])
@login_required
def play_post():

    game_form         = GameForm()
    pending_game_form = PendingGameForm()

    # True if game form submit button has been pressed
    if game_form.submit.data:
        # Validate form
        if game_form.validate():
            # Restore game from the session
            current_game = session.get('current_game')
            hangman = Hangman(**current_game)

            try:
                hangman.guessWord(user_guess_char = game_form.guess_character.data)
            except RefreshTokenExpiredError as e:
                # Refresh token expired, we have to log in again
                flash('Session expired. Log in again','is-danger')
                return redirect(url_for('auth.logout'))
            except Exception as e:
                flash("Something went wrong submitting your guess character. {}".format(e), 'is-danger')
            if hangman.status == 'WON':
                flash('{}, you are awesome! You won the game scoring {} points.'.format(session.get('user_name'),hangman.score), 'is-success')
            elif hangman.status == 'LOST':
                flash('{}, you are a loser'.format(session.get('user_name')), 'is-danger')

        else:
            flash('We can not validate your guess:', 'is-danger')
            for fieldName, errorMessages in game_form.errors.items():
                for errorMessage in errorMessages:
                    flash('{} - {}'.format(fieldName,errorMessage), 'is-danger')

    # If submit button from game_form not pressed then pending game form has been submitted
    elif pending_game_form.validate():
        new_game     = pending_game_form.new_game.data
        restore_game = pending_game_form.restore_game.data
        game_id      = pending_game_form.game_id.data

        # New game button pressed
        if new_game:
            flash('Starting new game', 'is-success')
            hangman = Hangman()
            try:
                hangman.startGame()
            except RefreshTokenExpiredError as e:
                # Refresh token expired, we have to log in again
                flash('Session expired. Log in again','is-danger')
                return redirect(url_for('auth.logout'))
            except Exception as e:
                flash('Failed to start game. {}'.format(e),'is-danger')
                return render_template('home.html')

        # Restore game button pressed
        elif restore_game:
            hangman = Hangman()
            hangman.loadGame(game_id)

    # Reset form
    game_form.guess_character.data = ''
    return render_template('play.html', hangman = hangman, form = game_form)

app/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Hangman webgame</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css"/>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
    <script src="{{ url_for('static', filename='js/main.js') }}"></script>
</head>

<body>
    <section class="hero is-primary is-fullheight">

        <div class="hero-head has-background-grey-dark">
            <nav class="navbar">
                <div class="container">

                    <div id="navbarMenuHeroA" class="navbar-menu">
                        <div class="navbar-end">
                            <a href="{{ url_for('gui.home') }}" class="navbar-item">
                                Home
                            </a>
                            {% if current_user.is_authenticated %}
                            <a href="{{ url_for('gui.play') }}" class="navbar-item">
                                New game
                            </a>
                            {% endif %}
                            {% if current_user.is_authenticated %}
                            <a href="{{ url_for('gui.halloffame') }}" class="navbar-item">
                                Hall of fame
                            </a>
                            {% endif %}
                            {% if not current_user.is_authenticated %}
                            <a href="{{ url_for('auth.login') }}" class="navbar-item">
                                Login
                            </a>
                            <a href="{{ url_for('auth.signup') }}" class="navbar-item">
                                Sign Up
                            </a>
                            {% endif %}
                            {% if current_user.is_authenticated %}
                            <a href="{{ url_for('auth.logout') }}" class="navbar-item">
                                Logout
                            </a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </nav>

            {% with messages = get_flashed_messages(category_filter=["is-danger"]) %}
                {% if messages %}
                    <div class="notification is-danger">
                        <button class="delete"></button>
                        <ul class=flashes>
                            {% for message in messages %}
                            <li>{{ message }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}
                {% endwith %}

                {% with messages = get_flashed_messages(category_filter=["is-success"]) %}
                {% if messages %}
                    <div class="notification is-success">
                        <button class="delete"></button>
                        <ul class=flashes>
                            {% for message in messages %}
                            <li>{{ message }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}
            {% endwith %}
        </div>

        <div class="hero-body">
            <div class="container has-text-centered">
               {% block content %}
               {% endblock %}
            </div>
        </div>
    </section>
</body>

</html>

app/templates/halloffame.html
{% extends "base.html" %}

{% block content %}
<h1 class="title">
    Hall of Fame
</h1>

<div class="container">
    <div class="columns is-centered">
        <table class="table">
            <thead>
                <tr class="has-background-info">
                    <th>Ranking</th>
                    <th>Username</th>
                    <th>Score</th>
                </tr>
            </thead>
            <tbody>
            {% for game in games %}
                <tr class="{{ loop.cycle('has-background-white-bis','has-background-white-ter') }}">
                    <th class="has-text-right">#{{ loop.index }}</th>
                    <td class="has-text-left">{{ game['user']['name'] }}</td>
                    <td class="has-text-right">{{ game.score | string }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

app/templates/home.html
{% extends "base.html" %}

{% block content %}
<h1 class="title">
	Home
</h1>
<h2 class="subtitle">
	This the main hangman screen
</h2>
{% endblock %}

app/templates/login.html
{% extends "base.html" %}

{% block content %}
<div class="column is-4 is-offset-4">
    <h3 class="title">Login</h3>
    <div class="box">
        <form method="POST" action="/login">
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="email" name="email" placeholder="Your Email" autofocus="">
                </div>
            </div>
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="password" name="password" placeholder="Your Password">
                </div>
            </div>
            <div class="field">
                <label class="checkbox">
                    <input type="checkbox">
                    Remember me
                </label>
            </div>
            <button class="button is-block is-info is-large is-fullwidth">Login</button>
        </form>
    </div>
</div>
{% endblock %}

app/templates/pending_game.html
{% extends "base.html" %}

{% block content %}
<div class="column is-4 is-offset-4">
    <h3 class="title">Pending game</h3>
    <div class="box">
        <div>Game #{{game.id}} was not finished. Would you like to continue where you left or play a new game ?</div>
        <form method="POST" action="/play">
            {{ form.hidden_tag() }}
            {{ form.new_game(class_="button is-block is-info is-large is-fullwidth") }}
            {{ form.restore_game(class_="button is-block is-info is-large is-fullwidth") }}
        </form>
    </div>
</div>
{% endblock %}

app/templates/play.html
{% extends "base.html" %}

{% block content %}
<h1 class="title">
	Playing Hangman: 
</h1>
<h2 class="subtitle">
	<p>game #{{ hangman.id }}</p>
</h2>

<div class="columns play-area">
	<div class="column is-half is-centered">
		<img class="hangman misses{{ hangman.misses | string }}">
	</div>
	<div class="column is-half">
		<div>
			<p class="has-text-black is-size-2">
				Score: {{ hangman.score | string }}
			</p>
			<p class="has-text-black">
				Multiplier: x{{ hangman.multiplier | string }}
			</p>
		</div>
		<section class="section">
			<div class="columns is-centered">
				<div class="column is-narrow">
				<table class="table is-bordered">
					<tr>
					{% for char in hangman.secret_word %}
						{% if loop.index0 in hangman.get_word_mask() %}
						<td> </td>
						{% else %}
						<td>{{ char }}</td>
						{% endif %}	 
					{% endfor %}
					</tr>
				</table>
				</div>
			</div>
		</section>
	
		{% if hangman.status == 'ACTIVE' %}
		<form action="" method="post">
			
			{{ form.hidden_tag() }}
		
			<div class="field is-grouped">
				<p class="control is-expanded">
					{{ form.guess_character(class_="input is-rounded has-text-centered", maxlength=1, autofocus=true) }}
				</p>
				<p class="control">
					{{ form.submit(class_="button is-link") }}
				</p>
			  </div>	  
		</form>
		{% endif %}
	</div>
	
</div>
{% endblock %}

app/templates/signup.html
{% extends "base.html" %}

{% block content %}
<div class="column is-4 is-offset-4">
    <h3 class="title">Sign Up</h3>
    <div class="box">
        <form method="POST" action="/signup">
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="email" name="email" placeholder="Email" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="text" name="name" placeholder="Name" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="password" name="password" placeholder="Password">
                </div>
            </div>

            <button class="button is-block is-info is-large is-fullwidth">Sign Up</button>
        </form>
    </div>
</div>
{% endblock %}